name: Construir APK de Android

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Esto habilita un botón manual para iniciar si quieres

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar código
      uses: actions/checkout@v4

    - name: Preparar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.x'

    - name: Instalar Flet y librerías
      run: |
        pip install flet gspread

    - name: Construir la APK
      run: |
        flet build apk --org "com.inventario.app" --project "Inventario"

    - name: Subir la APK lista
      uses: actions/upload-artifact@v4  # <--- AQUÍ ESTABA EL ERROR (Ahora es v4)
      with:
        name: app-inventario-release
        path: build/apk/*.apk
